### ISSUE TITLE
Potential non-terminated sql query.

### ISSUE THREAD

**Issue by cdbridger-tracplus** [zzzprojects/Dapper-Plus#151]
For context: We just started running PgCat https://github.com/postgresml/pgcat infront of our Cloud SQL postgres db which seems to be working fine except in one case. When we run a bulk insert on one of our tables.

```
await readDatabase.BulkInsert(geofenceMetrics);
```

model for reference

```
[Table("geofence_events", Schema = "geofencing")]
public class GeofenceMetric
{
    [Column("id")]
    public Guid? Id { get; set; }
    [Column("source_id")]
    public Guid SourceId { get; init; }
    [Column("date_estimated")]
    public DateTime? DateEstimated { get; init; }
    [Column("asset_id")]
    public long AssetId { get; init; }
    [Column("geofence_id")]
    public long GeofenceId { get; init; }
    [Column("geofence_version_id")]
    public long GeofenceVersionId { get; init; }
    [Column("geofence_name")]
    public string GeofenceName { get; init; }
    [Column("geofence_organisation_id")]
    public string GeofenceOrganisationId { get; init; }
    [Column("asset_direction")]
    public string? AssetDirection { get; init; }
    [Column("geofence_boundary_location")]
    public string? GeofenceBoundaryLocation { get; init; }
    [Column("geofence_boundary_type")]
    public int? GeofenceBoundaryType { get; init; }
    [Column("latitude_estimated")]
    public double? LatitudeEstimated { get; init; }
    [Column("longitude_estimated")]
    public double? LongitudeEstimated { get; init; }
    [Column("altitude_estimated")]
    public double? AltitudeEstimated { get; init; }
    [Column("elevation_estimated")]
    public double? ElevationEstimated { get; init; }
}
```
    
The error we get is:

```
    File: "utility.c"
InvariantSeverity: "ERROR"
Line: "458"
MessageText: "cannot execute COPY during recovery"
Routine: "PreventCommandDuringRecovery"
Severity: "ERROR"
SqlState: "25006"
}
ErrorCode: -2147467259
File: "utility.c"
HResult: -2147467259
InternalPosition: 0
InvariantSeverity: "ERROR"
IsTransient: false
Line: "458"
Message: "25006: cannot execute COPY during recovery"
MessageText: "cannot execute COPY during recovery"
Position: 0
Routine: "PreventCommandDuringRecovery"
Severity: "ERROR"
Source: "Npgsql"
SqlState: "25006"
StackTrace: "   at Npgsql.Internal.NpgsqlConnector.ReadMessageLong(Boolean async, DataRowLoadingMode dataRowLoadingMode, Boolean readingNotifications, Boolean isReadingPrependedMessage)
   at System.Runtime.CompilerServices.PoolingAsyncValueTaskMethodBuilder`1.StateMachineBox`1.System.Threading.Tasks.Sources.IValueTaskSource<TResult>.GetResult(Int16 token)
   at Npgsql.NpgsqlBinaryImporter.Init(String copyFromCommand, Boolean async, CancellationToken cancellationToken)
   at Npgsql.NpgsqlConnection.BeginBinaryImport(Boolean async, String copyFromCommand, CancellationToken cancellationToken)
   at Npgsql.NpgsqlConnection.BeginBinaryImport(String copyFromCommand)
   at InvokeStub_NpgsqlConnection.BeginBinaryImport(Object, Span`1)
   at System.Reflection.MethodBaseInvoker.InvokeWithOneArg(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)"
TargetSite: "Void MoveNext()"
Type: "Npgsql.PostgresException"
}
Message: "Exception has been thrown by the target of an invocation."
Source: "System.Private.CoreLib"
StackTrace: "   at System.Reflection.MethodBaseInvoker.InvokeWithOneArg(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at .( , DbConnection , DbTransaction )
   at .Execute(List`1 actions)
   at Z.BulkOperations.BulkOperation.Execute()
```
    
The working theory is that PgCat is mistakenly routing the insert query to the read-only replica which is what causes this error to throw. Investigating further we get is error from PgCat
    
```
     Query parsing error: QueryRouterParserError("sql parser error: Expected ;, found: EOF") (client: { application_name: pgcat, username: postgres
```

So I went an applied this to our application:

```
DapperPlusManager.Entity<GeofenceMetric>()
    .UseBulkOptions(
        options =>
        {
            options.Log = logger.Debug;
        }
    );
```

and it spits out these just before the error happens:

```
-- Executing Command:
SELECT * FROM "geofencing"."geofence_events" LIMIT 0;

-- CommandTimeout:30
-- Executing at 11/07/2024 06:00:00
```

and

```
-- Executing Command:

SELECT	
	table_schema AS "BaseSchemaName",
	table_name AS "BaseTableName",
	column_name AS "ColumnName",
	data_type AS "DateType",
	ordinal_position AS "Ordinal",
    udt_name AS "UdtName",
	CASE WHEN EXISTS (
		SELECT 1 FROM
		INFORMATION_SCHEMA.TABLE_CONSTRAINTS X 
		JOIN INFORMATION_SCHEMA.CONSTRAINT_COLUMN_USAGE AS Y USING (constraint_schema, constraint_name) 
		WHERE X.constraint_type = 'PRIMARY KEY' AND X.table_name = A.table_name AND Y.column_name = A.column_name) 
	THEN 1 ELSE 0 END AS "IsKey",
    CASE WHEN pg_get_serial_sequence('"geofencing"."' || TABLE_NAME || '"', COLUMN_NAME) IS NOT NULL
    THEN 1 ELSE 0 END AS "IsIdentity",
    is_nullable AS "AllowDBNull"
FROM INFORMATION_SCHEMA.COLUMNS AS A
WHERE TABLE_SCHEMA = 'geofencing' AND  TABLE_NAME = 'geofence_events'

-- CommandTimeout:30
-- Executing at 11/07/2024 06:00:00
```

and I noticed that the second query has no terminating semi colon (where as the first one does). I realise I could be chasing a red-herring but it does seem to line up with the PgCat error expecting a semicolon but getting EOF. (to which my theory would be  that pgCat fails to parse the queries, and reverts to its default behaviour and route the transaction to either the master or the read replica as it usually does, and in the cases when the read-replica receives it, the replica then throws the error). 

So i guess my question is, is there actually a semi-colon missing(or maybe its just the logging not logging it out), and if so, could this please be fixed?

Cheers for all your help!

**Comment by JonathanMagnan** [comment]
Hello @cdbridger-tracplus ,

Thank you for reporting it.

Like you, I'm not sure if that's the problem, but I agree that's surely our best guess for trying it. We will review all our queries to ensure they end with a semicolon (which around 95% of them already do).

Best Regards,

Jon

**Comment by cdbridger-tracplus** [comment]
Is there any ETA/Update?

Cheers

**Comment by JonathanMagnan** [comment]
Hello @cdbridger-tracplus ,

One of my developers has made a pull request. It will be reviewed tomorrow, and the fix probably be released (if accepted) on Tuesday.

Best Regards,

Jon

**Comment by JonathanMagnan** [comment]
Hello @cdbridger-tracplus ,

The v7.5.5 is now available.

Could you try it and let us know if everything is now working?

Best Regards,

Jon

**Comment by cdbridger-tracplus** [comment]
Well can definitely see the added semi colon in the logs! Thank you very much for that! Unfortunately the query parse that pgCat is still not handling it well. We will have to chase down other avenues. Thank you very much for your time and effort none the less!
