### ISSUE TITLE
IDbConnectionFactory > The Provider could not be resolved. You must explicitly set the Provider

### ISSUE THREAD

**Issue by ltond** [zzzprojects/Dapper-Plus#89]
We are seeing this error

`The Provider could not be resolved. You must explicitly set the Provider.'`

when trying to call `DbConnection.BulkInsert` using the Dapper Plus library.

DbConnection here is created via a IDbConnectionFactory - CreateConnection() method. We are bootstrapping the DbConnectionFactory as follows:

```
services.AddDbConnectionFactory(
    _ => new SqlConnection(Configuration.GetConnectionString("xxx")));
```

Exception stack trace:
```
   at Z.BulkOperations.BulkOperation.()
   at Z.BulkOperations.BulkOperation.Execute()
   at Z.BulkOperations.BulkOperation.BulkInsert()
   at Z.Dapper.Plus.DapperPlusAction.Execute()
   at Z.Dapper.Plus.DapperPlusActionSet`1.DapperPlusActionSetBuilder(DapperPlusContext context, IDbConnection connection, IDbTransaction transaction, String mapperKey, DapperPlusActionKind actionKind, IEnumerable`1 items, Func`2[] selectors)
   at Z.Dapper.Plus.DapperPlusActionSet`1..ctor(DapperPlusContext context, IDbConnection connection, String mapperKey, DapperPlusActionKind actionKind, IEnumerable`1 items, Func`2[] selectors)
   at Z.Dapper.Plus.DapperPlusExtensions.BulkInsert[T](IDbConnection connection, String mapperKey, IEnumerable`1 items, Func`2[] selectors)
   at Z.Dapper.Plus.DapperPlusExtensions.BulkInsert[T](IDbConnection connection, IEnumerable`1 items, Func`2[] selectors)
   at <<application code>>
 ```

**Comment by JonathanMagnan** [comment]
Hello @ltond ,

What's the `DbConnection` full name? Are you using something like MiniProfiler or your use your own custom connection?

Best Regards,

Jon

**Comment by ltond** [comment]
Hi, DbConnection.ToString():
`Dapper.Logging.Hooks.WrappedConnection`1[[Dapper.Logging.Empty, Dapper.Logging, Version=0.4.3.0, Culture=neutral, PublicKeyToken=9516ed96e39666d6]]`

It happens when running locally, the connection string is of the form `Server=localhost;Database=...;User Id=...;Password=...;`

**Comment by ltond** [comment]
From above it looks like we are using https://github.com/hryz/Dapper.Logging for the AddDbConnectionFactory extension method and the wrapper round the DbConnection. This was added for logging SQL queries to output - would we be better off switching to MiniProfiler?
